os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild -project SmartHint.xcodeproj -scheme SmartHint -sdk iphonesimulator14.2 -destination 'platform:macOS, arch:x86_64, variant:Mac Catalyst, id:42213BA8-B04C-8010-8F07-C34FB171DD80' test
