os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild -project SmartHint.xcodeproj -scheme SmartHint -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.2' test
