os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild -project SmartHint.xcodeproj -scheme SmartHint -sdk iPhone Simulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.0' test
